name: rupiyo_seller
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:

  flutter:
    sdk: flutter
  mysql1: ^0.20.0
  provider: ^6.1.1
  mapmyindia_gl: ^0.3.2 
  http:
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  address: ^0.1.0+2
  shared_preferences: ^2.2.2
  csc_picker: ^0.2.7
  fluttertoast: ^8.2.4
  email_validator: ^2.1.17
  page_transition: ^2.1.0
  url_launcher: ^6.2.2
  sms_otp_auto_verify: ^2.1.0

  #Firebase Plugins Start Here
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  image_picker: ^0.8.4+3
  bloc: ^8.1.2
  #Firebase Plugins Ends Here
  
  flutter_spinkit: ^5.2.0
  flutter_staggered_animations: ^1.0.0
  dropdown_search: ^5.0.6
  easy_loading_button: ^0.3.2
  permission_handler: ^11.0.0 
  gap: ^3.0.1
  flutter_animate: ^4.3.0
  auto_size_text: ^3.0.0
  toast: ^0.3.0
  path: ^1.8.3
  lottie: ^2.7.0
  pin_code_fields: ^7.3.0
  im_stepper: ^1.0.1+1
  intl_phone_number_input: ^0.7.3+1




  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Assets/Images/
    - Assets/Audio/
    - Assets/Fonts/
    - Assets/LottieAssets/



 
  fonts:
    - family: Poppins
      fonts:
        - asset: Assets/Fonts/Poppins-Regular.ttf
        - asset: Assets/Fonts/Poppins-Light.ttf
        - asset: Assets/Fonts/Poppins-Medium.ttf
        - asset: Assets/Fonts/Poppins-Bold.ttf
  